welcome: Hello and Welcome, feel free to wonder around. Any help use the tag #help in chat =) Please allow the server a few moments to collect your permissions

server:
  registered: false
  protection:
    enabled: true

protection:
  greif:true

logger:
  enabled: true
  onconnect: true
  ondisconnect: true
  chat: true
  url: http://cppmonkey.net/minecraft/update.php

override:
  nage: false

plugin:
  update:
    auto: true

boxy:
  tool: 279