name: MonkeyMod
main: me.cppmonkey.monkeymod.MonkeyMod
version: 0.1.1
author: CppMonkey
description: >
             An admin tool along with offering Cuboid like functions

commands:
  monkey:
    description: Executes MonkeyMod Command
    usage: |
           /<command> update
           /<command> uptodate
           /<command> status
           /<command> setvar [var] [val]
           /<command> enable [var]
           /<command> disable [var]
           /<command> add user [var]
           /<command> add vip [var]
           /<command> add admin [var]
           /<command> remove user [var]
           /<command> remove vip [var]
           /<command> remove admin [var]
  boxy:
    aliases: [boxie]
    description: Cuboid like function for replacing blocks
    usage: |
           /<command> <Replace ID> <With ID> [Height] [Spacing]
           /<command>:e <CSV list of blocks>
  chest:
    description: Adds chest protection to chests. Chests are locked by default. Use a bone you lock / unlock chests.
    usage: |
           /<command> lock
           /<command> unlock
           Example: /<command> lock
  item:
    description: Gives items to players
    usage: |
           /<command> <ItemID>[:data] [Quantity]
           Example: /<command> 1 64
  tele:
    description: Teleport to player
    usage: |
           /<command> <playername>
           Example: /<command> notch
  back:
    description: Teleports you back to where you tele'd from
    usage: |
           /<command> <playername>
           Example: /<command>
  spawn:
    description: Teleport to spawn
    usage: |
           /<command>
           Example: /<command>
  home:
    description: Sets your compass to point to your home ( 1 to 5)
    usage: |
           /<command> <set> <home number>
           /<command> <home number>
           Example: /<command> 1
  compass:
    description: Gives you a compass to find your way home
    usage: |
           /<command>
           Example: /<command>
  mode:
    description: Alters your game mode
    usage: |
           /<command>
           Example: /<command>
  message:
    description: Send a message to offline players
    usage: |
           /<command> <username:message>
           Example: /<command> admin:Help! My house has been greifed!
  inventory:
    description: Outputs a players inventory, and / or any risk items ( admins only )
    usage: |
           /<command> <player name>
           /<command> <playername> risk
           Example: /<command> notch
           Example: /<command> notch risk