name: MonkeyMod
main: me.cppmonkey.monkeymod.MonkeyMod
version: 0.1
author: CppMonkey
description: >
             An admit tool along with offering Cuboid like functions

commands:
  monkey:
    description: Executes MonkeyMod Command
    usage: |
           /<command> update
           /<command> uptodate
           /<command> status
           /<command> setvar [var] [val]
           /<command> enable [var]
           /<command> disable [var]
           /<command> add user [var]
           /<command> add vip [var]
           /<command> add admin [var]
  boxy:
    aliases: [boxie]
    description: Cuboid like function for replacing blocks
    usage: |
           /<command> <Replace ID> <With ID> [Height] [Spacing]
           Example: /<command> 0 1 10 2
  item:
    description: Gives items to players
    usage: |
           /<command> <ItemID> [Quantity]
           Example: /<command> 1 64