name: MonkeyMod
main: me.cppmonkey.monkeymod.MonkeyMod
version: 0.1
author: CppMonkey
description: >
             An admin tool along with offering Cuboid like functions

commands:
  monkey:
    description: Executes MonkeyMod Command
    usage: |
           /<command> update
           /<command> uptodate
           /<command> status
           /<command> setvar [var] [val]
           /<command> enable [var]
           /<command> disable [var]
           /<command> add user [var]
           /<command> add vip [var]
           /<command> add admin [var]
  boxy:
    aliases: [boxie]
    description: Cuboid like function for replacing blocks
    usage: |
           /<command> <Replace ID> <With ID> [Height] [Spacing]
           Example: /<command> 0 1 10 2
  chest:
    description: Adds chest protection to chests
    usage: |
           /<command> allow <PlayerName>
           /<command> block <PlayerName>
           Example: /<command> allow Notch
  item:
    description: Gives items to players
    usage: |
           /<command> <ItemID>[:data] [Quantity]
           Example: /<command> 1 64
  plugin:
    description: Reload plugins
    usage: |
           /<command> [reload] [plugin]
           Example: /<command> reload MonkeyMod